Resources:
  ItemModelTable3:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "name"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "name"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "ItemModelTable3"
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          const AWS = require("aws-sdk");
          const response = require('./cfn-response');
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event,null,2));
            var params = {
              RequestItems: {
                "ItemModelTable3": [
                  {
                    PutRequest: {
                      Item: {
                        name: "Shield",
                        healthMod: 0,
                        defenseMod: 30,
                        attackDamageMod: 0,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Sword",
                        healthMod: 0,
                        defenseMod: 0,
                        attackDamageMod: 20,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Dagger",
                        healthMod: 0,
                        defenseMod: 0,
                        attackDamageMod: 0,
                        attackSpeedMod: 15
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Belt",
                        healthMod: 100,
                        defenseMod: 0,
                        attackDamageMod: 0,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Reinforced Spike Shield",
                        healthMod: 30,
                        defenseMod: 100,
                        attackDamageMod: 10,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Lance & Shield",
                        healthMod: 100,
                        defenseMod: 50,
                        attackDamageMod: 40,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Parrying Shield",
                        healthMod: 50,
                        defenseMod: 35,
                        attackDamageMod: 0,
                        attackSpeedMod: 25
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Fortyfing Bulwark",
                        healthMod: 150,
                        defenseMod: 60,
                        attackDamageMod: 10,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Great Sword",
                        healthMod: 200,
                        defenseMod: 30,
                        attackDamageMod: 80,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Balanced Rapier",
                        healthMod: 0,
                        defenseMod: 15,
                        attackDamageMod: 50,
                        attackSpeedMod: 25
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Inspiring Banner",
                        healthMod: 300,
                        defenseMod: 20,
                        attackDamageMod: 40,
                        attackSpeedMod: 0
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Twin Daggers",
                        healthMod: 0,
                        defenseMod: 20,
                        attackDamageMod: 30,
                        attackSpeedMod: 70
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Inspiring Banner",
                        healthMod: 150,
                        defenseMod: 30,
                        attackDamageMod: 0,
                        attackSpeedMod: 45
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        name: "Suspenders of Hope",
                        healthMod: 500,
                        defenseMod: 80,
                        attackDamageMod: 30,
                        attackSpeedMod: 0
                      }
                    }
                  }                  
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                response.send(event, context, "FAILED", {});
              } else {
                response.send(event, context, "SUCCESS", {});
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      # 2020-02-27: [bp] updated from nodejs10.x in case it matters
      Runtime: nodejs12.x
      Timeout: 60
  InitializeItemModelTable3:
    Type: Custom::InitFunction
    DependsOn: ItemModelTable3
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitFunction , "Arn" ]
      DynamoTableName:
        Ref: ItemModelTable3